apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bkh2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bkh2
    app.kubernetes.io/part-of: tkrw-pr712-0075-0035-app
  name: devfile-sample-bkh2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bkh2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bkh2
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-bkh2@sha256:f50ce4d300b1c79a33f6c63ba8675fadc2fda9d08df06423dac48aa7f9c26f25
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
